filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/system_monitor.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
